version: '2'
services:

  # mysql
  mysql:
    image: "mysql:5.7.10"
    container_name: "typeorm-mg-mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "test"

  # mariadb
  mariadb:
    image: "mariadb:10.1.16"
    container_name: "typeorm-mg-mariadb"
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "test"

  # postgres
  postgres:
    image: "mdillon/postgis:9.6"
    container_name: "typeorm-mg-postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"

  # mssql
  mssql:
    image: "mcr.microsoft.com/mssql/server:2017-GA-ubuntu"
    container_name: "typeorm-mg-mssql"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Admin12345"
      ACCEPT_EULA: "Y"

  # oracle
  oracle:
    image: "store/oracle/database-enterprise:12.2.0.1-slim"
    container_name: "typeorm-mg-oracle"
    ports:
      - "1521:1521"
    environment:
        DB_SID: "sys"
        SYS_PASSWORD: "ORCLCDB"

  oracle_client:
    image: "store/oracle/database-instantclient:12.2.0.1"
    container_name: "typeorm-mg-oracle-client"

